# Use the official MongoDB image
FROM mongo:7.0

# Optional: set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=mongo
ENV MONGO_INITDB_ROOT_PASSWORD=mongo

# Expose default MongoDB port
EXPOSE 27017

# Start MongoDB
CMD ["mongod"]
